# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-13 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='quantidade_cpu',
            field=models.PositiveIntegerField(verbose_name='Quantidade de CPU'),
        ),
    ]
