# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0003_auto_20160713_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Provedor')),
            ],
            options={
                'db_table': 'provedor',
            },
        ),
        migrations.AlterField(
            model_name='servidor',
            name='quantidade_cpu',
            field=models.IntegerField(verbose_name='Quantidade de CPU'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='provedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='comparador.Provedor', verbose_name='Provedor'),
            preserve_default=False,
        ),
    ]
