# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0004_auto_20160714_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='logo',
            field=models.ImageField(default=None, upload_to=b'', verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
